# Generated by Django 4.2.30 on 2026-06-09 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, help_text='Optional logo URL for the tenant.', max_length=500, null=True)),
                ('visual_config', models.JSONField(blank=True, default=dict, help_text='Tenant visual configuration containing colors, branding elements.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='open', help_text='Status of the issue (e.g. open, in_progress, resolved).', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the issue.')),
                ('photo_url', models.URLField(blank=True, help_text='Optional link to a uploaded photo showing the issue.', max_length=500, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Tenant-specific dynamic key-value fields.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant this issue belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False, help_text='Whether this field must be filled when submitting an issue.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that defines this custom field.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
