# Generated by Django 4.2.30 on 2026-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='es', help_text='Default language for the tenant interface.', max_length=5),
        ),
    ]
