# Generated by Django 4.2.30 on 2026-06-10 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_default_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Employee user (operator) assigned to resolve this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='secure_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Secure passwordless lookup token for operators.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', help_text='Status of the issue (e.g. pending, in_progress, resolved).', max_length=50),
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for notification/integration (e.g. WhatsApp).', max_length=20, null=True)),
                ('user', models.OneToOneField(help_text='User associated with this operator profile.', on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
