# Generated by Django 4.2.30 on 2026-06-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_issue_assigned_to_issue_secure_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded photo evidence of the issue.', null=True, upload_to='issues/'),
        ),
    ]
