# Generated by Django 4.2.30 on 2026-06-16 11:56

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    OperatorProfile = apps.get_model('core', 'OperatorProfile')
    for row in OperatorProfile.objects.all():
        row.hub_token = uuid.uuid4()
        row.save(update_fields=['hub_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_issue_image'),
    ]

    operations = [
        # 1. Add field allowing null and not unique
        migrations.AddField(
            model_name='operatorprofile',
            name='hub_token',
            field=models.UUIDField(default=uuid.uuid4, null=True, editable=False, help_text='Unique UUID token for passwordless operator dashboard access.'),
        ),
        # 2. Populate unique UUIDs for existing rows
        migrations.RunPython(gen_uuid, elidable=True),
        # 3. Alter field to unique=True and null=False
        migrations.AlterField(
            model_name='operatorprofile',
            name='hub_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, null=False, editable=False, help_text='Unique UUID token for passwordless operator dashboard access.'),
        ),
    ]
