# Generated by Django 4.2.30 on 2026-06-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_operatorprofile_hub_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='order_index',
            field=models.IntegerField(db_index=True, default=0, help_text='Custom priority ordering index.'),
        ),
    ]
