# Generated by Django 4.2.30 on 2026-06-23 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_issue_order_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('blocked', 'Blocked')], default='pending', help_text='Status of the issue (e.g. pending, in_progress, resolved).', max_length=50),
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text='The actual text content of the note/comment.')),
                ('is_system_log', models.BooleanField(default=False, help_text='Whether this entry was auto-generated by the system as an audit event.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_operator', models.ForeignKey(blank=True, help_text='Operator who authored this comment, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.operatorprofile')),
                ('author_user', models.ForeignKey(blank=True, help_text='User (manager/admin) who authored this comment, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(help_text='The issue this comment/log belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.issue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
