# Generated by Django 4.2.30 on 2026-06-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_issue_status_issuecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('blocked', 'Blocked'), ('wont_fix', 'Wont Fix')], default='pending', help_text='Status of the issue (e.g. pending, in_progress, resolved, wont_fix).', max_length=50),
        ),
    ]
