# Generated by Django 4.2.30 on 2026-07-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the issue was resolved or marked wont_fix.', null=True),
        ),
    ]
