# Generated by Django 4.2.30 on 2026-07-07 10:36

from django.db import migrations, models


def backfill_titles(apps, schema_editor):
    Issue = apps.get_model('core', 'Issue')
    for issue in Issue.objects.all():
        if not issue.title:
            issue.title = issue.description[:50]
            issue.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_backfill_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Concise summary title of the issue.', max_length=100),
        ),
        migrations.RunPython(backfill_titles),
    ]
