# Generated by Django 4.2.30 on 2026-07-09 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cached total material/labor cost logged for this task.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='total_time_spent_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cached total effective time logged in hours for this task.', max_digits=7, null=True),
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text description or update comment.')),
                ('image', models.ImageField(blank=True, help_text='Uploaded evidence or proof of work photo.', null=True, upload_to='task_logs/')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Incremental material or service cost for this step.', max_digits=8, null=True)),
                ('time_spent_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Incremental effective labor time spent in hours (e.g. 1.5).', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the log was created.')),
                ('author_type', models.CharField(choices=[('MANAGER', 'Manager'), ('OPERATOR', 'Operator')], default='OPERATOR', help_text='Role type of the author.', max_length=20)),
                ('author_operator', models.ForeignKey(blank=True, help_text='Operator profile who created this log, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_logs', to='core.operatorprofile')),
                ('author_user', models.ForeignKey(blank=True, help_text='Admin/Manager user who created this log, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='The task (issue) this log belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.issue')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
