# Generated by Django 4.2.30 on 2026-07-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_issue_total_cost_issue_total_time_spent_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when execution completed (or submitted to QA).', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='order_number',
            field=models.CharField(blank=True, help_text='Auto-generated sequential order identifier (e.g. WO-00042).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='qa_checklist',
            field=models.TextField(blank=True, default='', help_text='Custom verification checklist steps specified by manager, separated by line breaks.'),
        ),
        migrations.AddField(
            model_name='issue',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when execution started.', null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('qa', 'QA / Verification'), ('resolved', 'Resolved'), ('blocked', 'Blocked'), ('wont_fix', 'Wont Fix')], default='pending', help_text='Status of the issue (e.g. pending, in_progress, qa, resolved, wont_fix).', max_length=50),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this zone/facility area.', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Physical zone/area associated with this issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='core.zone'),
        ),
    ]
